### ISSUE TITLE
Check if core is alive

### ISSUE THREAD

**Issue by banasiakadam60** [golemfactory/golem-electron#100]
When `golemapp` crash, UI doesn't show any notification. It should activly check if core is working and, if it crash/die it should tell about it

**Comment by mdtanrikulu** [comment]
@ederenn Can you check if it's possible to create a scenario like this and testing application?

**Comment by ederenn** [comment]
https://github.com/golemfactory/golem/issues/1592

**Comment by mdtanrikulu** [comment]
Alternatively resolved by #191.
