### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by banasiakadam60** [golemfactory/golem-electron#102]
After starting `Golem` I got error message:

![screenshot_20170920_153950](https://user-images.githubusercontent.com/11528913/30646686-17b927b6-9e1a-11e7-85fb-e3f15f12cbff.png)

But when I close it and wait, Golem is able to connect to other nodes and compute task (what means that everything works fine):

![screenshot_20170920_154250](https://user-images.githubusercontent.com/11528913/30646768-60fa0a9e-9e1a-11e7-85db-8f939a3fa300.png)

So this message is missleading. i'm not sure it it's UI problem or core problem, but it should be fixed.

**Comment by mdtanrikulu** [comment]
The error means that you have port forwarding problem. But it connects local nodes anyway, so we kept error skippable.
