### ISSUE TITLE
Easy access to golemapp logs in electron frontend

### ISSUE THREAD

**Issue by jiivan** [golemfactory/golem-electron#108]
Currently when electron frontend starts golemapp it captures it's stdout/stderr and there is no intuitive way to see why golemapp fails. I think that optional logging panel in the footer would help a lot. It may be also implemented as separate window that simply `tails` golemapp log.

**Comment by mdtanrikulu** [comment]
There's a PR called Log system (#64) which writes connection problems into the;
Windows   `%USERPROFILE%\.golem\logs\gui.log & gui-error.log `
Mac           `~/.golem/logs/gui.log & gui-error.log `
Linux         `~/.golem/logs/gui.log & gui-error.log `

For golemapp logs, it's open to the debate.

**Comment by mdtanrikulu** [comment]
![image](https://user-images.githubusercontent.com/2774845/52053027-7d3cd800-2558-11e9-9a8c-e86ba0bc35b0.png)
We added "open logs" redirection to golem/log folder directly from the footer bar. I think it'll make reaching out the files easy.
