### ISSUE TITLE
Waiting for geth startup

### ISSUE THREAD

**Issue by jiivan** [golemfactory/golem-electron#109]
As starting geth often takes significatn amount of time it will be more friendly to report it to user (`Geth starting up` status)

**Comment by etam** [comment]
It seems that there is reporting that geth is starting up, syncing and so on.

But if geth dies/is killed then there is no indication in golem-electron.

**Comment by etam** [comment]
Initial syncing was disabled (golemfactory/golem@8502d35a4202cbbe94914eda978268e14ad808ed). Now we're gonna use external geth nodes (PR golemfactory/golem#1524). There will be still support to start local geth, so I think we should get back to this once PR gets merged.
