### ISSUE TITLE
payments for subtasks, inconvenient design

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#121]
List of subtask payments (for one task) in history tab is very inconvenient to read, user needs to scroll down the whole list of subtasks, it looks rather messy.  For more than one task on list, it would be excruciating to look it trough. Better option would be payment in total for task - with some kind of drop-down menu with subpayments per task.

current design

<img width="497" alt="screen shot 2017-10-16 at 12 27 14" src="https://user-images.githubusercontent.com/32061891/31616455-0c50bb46-b28d-11e7-972e-02f98897a9f3.png">

**Comment by mdtanrikulu** [comment]
And other suggestion is usage of task ids as payment title is not clear. I suggest to show task name and owner name of computed sub-task pair on there.

**Comment by jamuszyn** [comment]
after brass
