### ISSUE TITLE
payments for subtasks, bug in scroll bar

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#122]
when hovering over subpayment list, subpayments tabs are obscuring scroll bar

![hoover](https://user-images.githubusercontent.com/32061891/31617278-1917456e-b28f-11e7-8cd1-20e83b7d65ae.png)

**Comment by mdtanrikulu** [comment]
Resolved 48a32c89c05b8295720e7ebd4ed77efe90553ab6.
