### ISSUE TITLE
preview window for frames is not refreshing 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#124]
To see progress, which frames are completed, which still wait for rendering, which are timed out, user need to refresh preview window manually. It would be nice to have it done automatically.

![2](https://user-images.githubusercontent.com/32061891/31626158-fd3fec8c-b2a8-11e7-91a4-3b16225df24d.jpg)

![3](https://user-images.githubusercontent.com/32061891/31626169-04194d14-b2a9-11e7-9cfb-881658079c06.jpg)

**Comment by mdtanrikulu** [comment]
Preview window doesn't refresh in other operating systems too. 
This issue is already in here #6.

I'm referencing old issue in here to merging both. Please update issue header without "mac".

**Comment by badb** [comment]
@mdtanrikulu Is this one resolved?

**Comment by mdtanrikulu** [comment]
@badb No, it's not yet.
