### ISSUE TITLE
renaming task, before starting it

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#130]
after clicking "next" button in naming task tab and setting some settings for task, it's impossible to change name of the task without loosing typed data (dimensions, frame range, timeout, etc). It's inconvenient, user may want to change task name after fixing some settings.

**Comment by mdtanrikulu** [comment]
It's somehow related with #13. Additional part is "going previous step while creating task". 

This comment is just a note for myself.

**Comment by jamuszyn** [comment]
Back button or wizard style with dots and steps - just to remember
