### ISSUE TITLE
if one task timed out, and the rest is preparing, golem is still showing timeout under preview

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#131]
if one task from list timed out, and the rest is preparing, golem is still showing only "your tas has timeouted" under preview
the same for windows and mac
 when user is highlighting a task it should be shown if its timed out, preparing for computations etc, as it is on a progress bar

![mulitipe timeout2](https://user-images.githubusercontent.com/32061891/31732715-bb62c932-b439-11e7-977c-b383e19360dd.png)
<img width="477" alt="screen shot 2017-10-18 at 18 40 41" src="https://user-images.githubusercontent.com/32061891/31732717-bf68c3b0-b439-11e7-9890-5f87a3cded07.png">

**Comment by mdtanrikulu** [comment]
It's a priority hierarchy of status.

Importance level going through; Timeout > Computing > Waiting > Preparing
Thus users will be aware if there's something they should interact with task or not.
