### ISSUE TITLE
fatal error, there are no instructions for user what to do after receiving one

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#133]
there should be provided information what to do after receiving a fatal error. Closing app is not a solution, after reopening app is still showing error. 
In my case it was a problem with geth blockchain syncing, after downloading new version of geth golem started working. User might not necessarily what to to in such a situation. For recurring errors there should be provided some solutions (maybe in troubleshooting) or at least a help address. (fatal error pop-up could have a link to site with common solutions)

**Comment by jamuszyn** [comment]
added to the list of errors to handle
