### ISSUE TITLE
second preview window is not working, mac

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#136]
for completed frames it is not possible to see preview in preview window - you receive empty window

<img width="1252" alt="screen shot 2017-10-20 at 21 18 20" src="https://user-images.githubusercontent.com/32061891/31838333-a42cfd92-b5dc-11e7-8361-cfd09fd71158.png">

<img width="1248" alt="screen shot 2017-10-20 at 21 18 03" src="https://user-images.githubusercontent.com/32061891/31838339-aa5cefce-b5dc-11e7-9a90-5ccbc6067f06.png">

**Comment by mdtanrikulu** [comment]
Is this a problem with binary or source?

**Comment by ederenn** [comment]
both. for sure there is problem with source version.

**Comment by mdtanrikulu** [comment]
Resolved.
