### ISSUE TITLE
Status inconsistent between network and task tab when stopped

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/golem-electron#141]
Running golem.app version `0.8.1` on mac os 10.13.

- Start golem.app
- Wait until started
- Stop golem with the button
- Wait until stopped
- Tasks tab shows "Golem is not started yet"
- Network tab shows "Connecting to network"

Screenshots:
![screen shot 2017-10-24 at 11 30 12](https://user-images.githubusercontent.com/10008353/31935426-174d482a-b8af-11e7-8f10-5bfb5dcccccf.png)
![screen shot 2017-10-24 at 11 30 21](https://user-images.githubusercontent.com/10008353/31935434-1a429468-b8af-11e7-9e3d-4e518c45224d.png)

**Comment by mdtanrikulu** [comment]
It seems like, your app didn't connect to the golem instance yet. Because it should show node information instead. On the other hand, we need to add some timeout there if there's no connection until x time period.

**Comment by maaktweluit** [comment]
Maybe i hit stop too soon before even connecting?

Very minor thing, so no priority needed. When you need any more debug information please let me know!

**Comment by mdtanrikulu** [comment]
Added "waiting for peer" info if there's no connected peers and/or no connection at all. #191
