### ISSUE TITLE
preview button is not active

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#142]
It's impossible to switch on preview window, button is not active. Regardless if it's computed for one frame or range of frames buton stays disabled. The same for mac and windows, source version, after all updates.
network was working, peers were connected, task computed.

![prev](https://user-images.githubusercontent.com/32061891/31969113-c875bc18-b913-11e7-8306-d961a6ce07b4.png)

![hrrfrr](https://user-images.githubusercontent.com/32061891/31969350-930bef88-b914-11e7-9be1-88c46b322947.png)

**Comment by mdtanrikulu** [comment]
Resolved 887298d6130d89197ae8665a4a9a26ccc5541542.
