### ISSUE TITLE
in settings, performance tab, CPU indicator is not working

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#144]
it stays on 0, on mac and on windows, source version

<img width="445" alt="screen shot 2017-10-25 at 14 30 35" src="https://user-images.githubusercontent.com/32061891/31998902-bdd63462-b991-11e7-9566-3a432c99b439.png">

**Comment by ederenn** [comment]
update, 21.11.2017 branch b0.9.1
performance indicators on windows are in calculating, never showing the result

![calculating](https://user-images.githubusercontent.com/32061891/33078036-c3bee0ae-ced1-11e7-9dd2-9f05c72cdf58.png)

on Mac, CPU still stays on 0

**Comment by mdtanrikulu** [comment]
Resolved (#183).
There's no CPU benchmark on first application initialization. To get first result, user needs to press calculate button on settings.
