### ISSUE TITLE
zoom out in preview window doesn't work well

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#145]
zooming out frame in preview window doesn't just decrease frame, it also multiplies it's view. Only one frame was computed, so it shouldn't be showing more than one object rendered. tested on source version

![ccc](https://user-images.githubusercontent.com/32061891/31999085-5e6d7f8e-b992-11e7-8abd-e1b00e995b49.jpg)

**Comment by mdtanrikulu** [comment]
Aprroved. Working on it.

**Comment by mdtanrikulu** [comment]
Resolved #172.
