### ISSUE TITLE
Can't save a preset after clearing a dimension field

### ISSUE THREAD

**Issue by etam** [golemfactory/golem-electron#147]
Steps to reproduce:
- load a preset
- select one of the dimensions field
- delete the number (this makes the "Save as preset" button grayed out)
- write something into the input field

Expected result: the "Save as preset" button gets unlocked

Actual result: button stays grayed out. The only way to unlock it is to load another preset or cancel task creation.

**Comment by mdtanrikulu** [comment]
Approved. Working on it.

**Comment by mdtanrikulu** [comment]
Resolved #147.
