### ISSUE TITLE
Starting Golem

### ISSUE THREAD

**Issue by gborowik** [golemfactory/golem-electron#150]
Despite Golem started, the frontend still says that 'Starting Golem'.

**Comment by gborowik** [comment]
This bug occurred on macOS High Sierra.

**Comment by gborowik** [comment]
The same problem occurs on macOS Sierra.

**Comment by mfranciszkiewicz** [comment]
Resolved in 154867ce2b8f1a8be7198adafa3f0af5a424c4ec
