### ISSUE TITLE
Start task opens browser

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/golem-electron#151]
On mac os 10.13 ( high sierra ) when running from source ( `dev` branch )
`file:///.../golem-electron/index.html` loads an empty page in my browser when "start task" is clicked.

**Comment by mdtanrikulu** [comment]
Are there any combination you're using while click, like holding shift etc. or is this happening when you just click? 

Did you start application server with `npm run start:app` ? 

I tried with High Sierra on dev branch, everything is as expected.

**Comment by maaktweluit** [comment]
Ran it with `npm run start:prod`, After updating the branch also ran `npm run compile` again
