### ISSUE TITLE
Subtask info popup cropped in preview window

### ISSUE THREAD

**Issue by etam** [golemfactory/golem-electron#154]
![screenshot_20171027_170949](https://user-images.githubusercontent.com/220752/32111584-2b7a4ac6-bb3b-11e7-9dbf-d7ddd22c050a.png)

**Comment by mdtanrikulu** [comment]
That's strange, probably calculating issue, I'll check it.

**Comment by mdtanrikulu** [comment]
Resolved #172, #178.
