### ISSUE TITLE
Restarting docker vm message gone too early

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/golem-electron#157]
Tested on windows from source.

When the docker-machine is restarting in the background ( can see in the logs ) the ui does not wait for the restart to finish before enabling the buttons again.

Expected behaviour:
Message about restart and enabling of the buttons happen when:
```
2017-11-09 14:28:07 DEBUG    golem.task.taskcomputer             b'Resuming new task computation'
```
is logged

Instead it happens much earlier

**Comment by mdtanrikulu** [comment]
Old issue, already resolved on core side.
