### ISSUE TITLE
Starting task too soon after boot does not test

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/golem-electron#158]
Running from 0.9.0 on mac OS ( but other platforms have the same )

When "starting golem" is going on it is possible to add a task. The test will not run until "X nodes connected" shows up.

Maybe the Task Name screen can be disabled / blocked until the app is ready to make tasks.

**Comment by mdtanrikulu** [comment]
Similar issue discussed [here](59) before, but we haven't add it yet. I'll implement it asap.

**Comment by mdtanrikulu** [comment]
Resolved #169.
