### ISSUE TITLE
build versions 0.10.0 are tagged with 0.9.1 tag

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#186]
In settings tab visible version tag is Brass Golem v0.9.1 instead of Brass Golem v 0.10.0

**Comment by maaktweluit** [comment]
Tag is applied as last step of the release / testing phase.
Yesterday EOD it was applied.

This morning the build still took the wrong tag, resolved in golemfactory/golem#1785

**Comment by maaktweluit** [comment]
Resolved with golemfactory/golem#1785 and golemfactory/golem#1788
