### ISSUE TITLE
Add task: Windows resources use wrong slashes

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/golem-electron#188]
Tested on windows with 0.1.5 binaries and golem 0.10.1 release candidate.

When adding a task as folder from the UI:
- Click On `(+)`
- Select the folder with .blend and resources

Resources are added with a wrong folder separator, this causes some to be double. Seen in this task file dump :

```
golemcli tasks dump UUID ./file.json
```
Result
```
{
   ...
    "resources": [
        "C:\\golem\\AtvBuggy/atv.png",
        "C:\\golem\\AtvBuggy/atv2.png",
        "C:\\golem\\AtvBuggy/buggy2.1.blend",
        "C:\\golem\\AtvBuggy\\buggy2.1.blend"
    ],
}
```

Expected
```
{
   ...
    "resources": [
        "C:\\golem\\AtvBuggy\\atv.png",
        "C:\\golem\\AtvBuggy\\atv2.png",
        "C:\\golem\\AtvBuggy\\buggy2.1.blend"
    ],
}
```

**Comment by mdtanrikulu** [comment]
Confirmed, working on it.
