### ISSUE TITLE
lag in GUI when uploading files with external assets or external textures

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#199]
render local test takes more than usual, counting in seconds
 at first sight, it seems like something was broken, file was eventually uploaded successfully

**Comment by mdtanrikulu** [comment]
@ederenn  Is this still continue?

**Comment by ederenn** [comment]
for "render local test" message it takes around 10 sec,
"checking" it seems quicker but it takes around 8 sec,
after that file is uploaded successfully, test passed
