### ISSUE TITLE
Duplicated task when restarted

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/golem-electron#207]
After task had a time out i did restart, and the task was duplicated. Now i have to tasks with the same name, one has "restarted" status, and the other is now "finished"
![zrzut ekranu 2018-01-30 o 12 50 54](https://user-images.githubusercontent.com/1597715/35565267-28c7a1e4-05bd-11e8-8d35-5f493161255d.png)

**Comment by mdtanrikulu** [comment]
Related #192.
