### ISSUE TITLE
Resubmit for subtasks is not working after timeout of a task 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#218]
In second preview window for subtasks, there's a possibility to resubmit a subtask. It is not working after timeout of a whole task - clicking it does nothing, no subtask restart, no task restart.
Before task timeout it is not necessary to have such a possibility, other nodes should undertake failed subtask.

<img width="756" alt="screen shot 2018-02-06 at 15 18 38 copy" src="https://user-images.githubusercontent.com/32061891/35867180-74980eaa-0b59-11e8-91ae-12e7d0580cfa.png">

**Comment by badb** [comment]
Please check the comment in original issue!
