### ISSUE TITLE
upgrade pop-up, no switch for "don't show me again"

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#237]
when higher version of Golem is available after every launch of application,on welcome screen it is shown pop-up with information about upgrade. It would be nice for user if  there would be a feature like "don't show me again"

![screen shot 2018-03-01 at 16 43 25](https://user-images.githubusercontent.com/32061891/36921984-9a848470-1e66-11e8-82ef-d8d0f35bb4af.jpg)

**Comment by jamuszyn** [comment]
tick with "don't show me again" and "ok" button should be enough

**Comment by mdtanrikulu** [comment]
We decided to not going with this idea, so new version modal will be move to notification center.
