### ISSUE TITLE
Task item-strange date

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/golem-electron#27]
After assigning task, on task list there is placed task item.

Under the task title there are some status/time information details.

After task is started, status change from waiting.. to "some_time Duration". It's not clear what is this time. I noticed that this is "Task timeout" time, but is it really duration? Task can be completed faster or not at all. Presenting task timeout as a duration doesn't seem much of a help, since user can see it in task details (besides he already know what timeout he has chosen). Can we consider more of something like ETA (estimated time of arrival?), but if this will be hard due to lack of information, maybe at least "elapsed time"? So user can now how long this task has already took time?

And some obvious bug, after task is completed, Duration is replaced with some strange "3.15 Pm Yesterday" ... which doesn't seems right this is set same for every task despite i have currently 10:59 AM on my clock and it seems to be right :). Should this be point in time when task was completed?

**Comment by mdtanrikulu** [comment]
"3.15 Pm Yesterday" was mockup and solved by 18ee71afe6b2a741fa852cee461c8b3fdf1d6929.
There will be another update for duration issue, there will be time remaining instead, but still team working on it in core.

**Comment by mdtanrikulu** [comment]
Continues on #129.
