### ISSUE TITLE
electron local storage problem - port warning

### ISSUE THREAD

**Issue by gborowik** [golemfactory/golem-electron#32]
The electron interface shows in a pulsed manner that the computer has not forwarded ports despite they are forwarded (macOS Sierra 10.12.5). Probably it is the problem with local storage.

**Comment by mdtanrikulu** [comment]
Could you check and share status of the connection on old GUI ?

**Comment by mfranciszkiewicz** [comment]
This issue occurs after clicking Stop => Start

**Comment by mdtanrikulu** [comment]
Yes, confirmed. When press `Start Golem`, until golem core actually restarts, application will show connection problem in this case.

**Comment by mdtanrikulu** [comment]
Resolved by 2cb68510476b3c637ffa8267abcee25fbd485414.
