### ISSUE TITLE
Allow to restart parts of the task after deadline

### ISSUE THREAD

**Issue by badb** [golemfactory/golem-electron#321]
There are three parts of this task.
1) User should be able to restart single subtask after deadline was hit. Same interface as in the previous solution should be used, it may just require different RPC call (not necessarily) or slightly different warning message. It should be done after https://github.com/golemfactory/golem/issues/2605 is implemented. 
2) Ability to restart all unfinished task after deadline. Proper GUI design for this option is required before implementation. 
3) Ability to choose set of subtasks that can be restarted after deadline was hit. Proper GUI design for this option is required before implementation.

**Comment by mdtanrikulu** [comment]
1. Resolved by #329.

**Comment by mdtanrikulu** [comment]
2. Resolved by 3287164a612f07cd1cec337c181978be3906d1a2.
