### ISSUE TITLE
adding file with + button after local render test, crashes interface

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#349]
### Steps to reproduce

reproducible on Windows and Mac OS, binaries 0.15.1

- add file in task tab either by drag and drop or by + button; click next 
- wait for local render test to be passed, don't start the task
- still, in the same tab with settings for file, click + button, add a file
- interface turns blank

![jhgjhgj](https://user-images.githubusercontent.com/32061891/40369051-6c84a7e2-5ddd-11e8-8eb7-588a928a4f06.PNG)

**Comment by maaktweluit** [comment]
i saw a similar issue last week, could you turn off developer/debug mode and reload? for me it showed again

**Comment by mdtanrikulu** [comment]
Resolved.
