### ISSUE TITLE
Blank screen // Refresh needed

### ISSUE THREAD

**Issue by jiivan** [golemfactory/golem-electron#364]
Immediately after startup main window stays blank (sometimes all white and sometimes all black).
Starts working after clicking `Refresh` a few times.

Blank
![empty1](https://user-images.githubusercontent.com/293058/41031095-24c522b6-6980-11e8-87a3-714cfb73621f.png)

Refresh
![empty2](https://user-images.githubusercontent.com/293058/41031122-30cf11b6-6980-11e8-8762-f0154f6d4608.png)

```
dariusz@ubuntu:~$ golemapp -v

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

GOLEM version: 0.15.1+dev324.g83bfaf3
```

**Comment by mdtanrikulu** [comment]
Is electron running over source or binary? If source, it is normal to see white screen until webpack creates a bundle of source code. 
If you are running binary please provide me info from developer tools (you can see it in menu in the shared picture above) and golem logs.

**Comment by jiivan** [comment]
It's binary running on virtual machine (vmplayer ubuntu 18.04 64bit). Haven't encountered this issue on native machine.
