### ISSUE TITLE
Trouble connecting with 7 connections established

### ISSUE THREAD

**Issue by jiivan** [golemfactory/golem-electron#365]
I have `golemapp` instance running for some time with 7 established connections (seen on the right side of screenshot).

After starting electron (`golem`) and handling #364 I'm greeted with `Trouble connecting` warning.

![empty3](https://user-images.githubusercontent.com/293058/41031340-aa139bfa-6980-11e8-96e6-e6248c7d4e5f.png)

After clicking this out and waiting about 30 seconds status updates to correct value:
![empty4](https://user-images.githubusercontent.com/293058/41031393-ccf6633c-6980-11e8-9c36-855735c8f9f2.png)

**Comment by mdtanrikulu** [comment]
I'm sorry but I couldn't get the issue.

If your ports are not redirected correctly, you will have "Trouble connecting" warning. But it skippable to serve other user interface interactions to users. So user interface will show the connected node amount afterwards, with "problem with ports" warning.

**Comment by jiivan** [comment]
Might be related to slowness of virtual machine.
