### ISSUE TITLE
Incorrect Golem version displayed

### ISSUE THREAD

**Issue by inexxt** [golemfactory/golem-electron#373]
After fresh install of golem, version displayed in the UI is `v0.1.12` - it probably should be `v0.1.16`.

**Comment by mdtanrikulu** [comment]
Hey @inexxt, ~~there is nothing wrong with the version number.~~ UI has It's own version and it is v0.1.12. You can find both versions on settings tab of electron.

Edit: There's one place needs to be change on footer, thanks for the observation.
