### ISSUE TITLE
Ability to restart selected subtasks from GUI. Pixel preview & subtask list preview. Subtask states

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/golem-electron#394]
*Task list with subtask details flow: 
https://invis.io/ECJHKMEWF4Y#/299124045_Task-List-Pixel-Preview

*Select multiple subtasks: 
https://invis.io/8PJHKO8FXT9#/299129306_Task-List-Subtask-Preview_02

*Subtask states: 
https://invis.io/PVJHKQM3XK4#/299129521_Task-List-Subtask-Details-Computing

**Comment by mdtanrikulu** [comment]
Related #321.
