### ISSUE TITLE
Testing on local machine

### ISSUE THREAD

**Issue by freedomtrain** [golemfactory/golem-electron#420]
Is there a way to test golem locally ....Can I start a server on my local machine and then connect to the server with the electron front end ?

Thanks !!!!

**Comment by mdtanrikulu** [comment]
Yes, for sure you can do it!

First way to do: You can run golem server from binary. To do it you should have [golem installed](https://github.com/golemfactory/golem/wiki/Installation#installers) on your machine, then run golem from terminal;

`golemapp` for testnet
`golemapp --mainnet` for mainnet

Second way: You can run golem server from source as well, to have it please follow [here](https://github.com/golemfactory/golem/wiki/Installation#running-from-the-source).


Now you can have golem electron repository and follow the instructions from [readme file](https://github.com/golemfactory/golem-electron/blob/dev/README.md).

If you would like to run 2 instances in the local machine and want to communicate only each other. Please follow [this instruction](https://github.com/golemfactory/golem/wiki/Creating-a-subnet-of-nodes).

**Comment by freedomtrain** [comment]
@mdtanrikulu Thanks so much for your help !
