### ISSUE TITLE
Golem hangs on "Connecting to network" on Windows

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/golem-electron#434]

**Comment by mdtanrikulu** [comment]
Selector implementation may solve the issue, 4a185aee471355bf2d5fdda584b2337905960829. Will be tested.

**Comment by shadeofblue** [comment]
this is resolved here: https://github.com/golemfactory/golem-electron/pull/438

**Comment by ederenn** [comment]
Happened again on rc 0.18.0
https://buildbot.golem.network/buildbot/#/builders/2/builds/2863

after stopping and starting Golem with button in interface was given "resource allocation error"
https://github.com/golemfactory/golem/issues/3108
Restart was needed and after restart of application, in interface Golem hangs on "Connecting to network". Logs are created normally. After restart of electron (crtl R) Golem shows connection to other nodes.
