### ISSUE TITLE
Improve Network > Advanced empty state

### ISSUE THREAD

**Issue by mattatgit** [golemfactory/golem-electron#45]
![advanced_empty_state](https://user-images.githubusercontent.com/6858525/27896258-202c7be0-625c-11e7-89cb-4b65051c1082.png)

1. “Not Loaded” is a bit clunky, better to say “No presets created”
2. Remove the  horizontal rule above “Manage Presets” if there is no preset (it looks awkward)
3. Make some auto-generated presets i.e. Light, Medium, Heavy (this would solve 1 & 2)

**Comment by mdtanrikulu** [comment]
2. Resolved by 57c02f73b51beec2038e756512f9908d000d2065.
3. There's some default presets but they're populated after connected to core.
