### ISSUE TITLE
Electron cannot start mainnet Golem, certificate problem

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#452]
####: Encountered on 
Linux, Mac OS, Widows:

binaries for linux core
https://buildbot.golem.network/artifacts/b0.18.0/golem-0.18.0-linux.tar.gz
binaries for electron
https://github.com/golemfactory/golem-electron/releases/download/untagged-7c1fa510886f72def6e4/linux-unpacked.tar.gz

steps to reproduce:
- switch all files in Golem binaries folder - both for core and electron
- run Golem mainnet 

from Linux console:
```
ederenn@ubuntu:~$ golem --mainnet
(node:8586) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, open '/home/ederenn/.local/share/golem/default/rinkeby/crossbar/secrets/electron.tck'
(node:8586) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
IPC Handlers created.
Golem error: 2
```

on every OS mainnet Golem is not starting, same steps to reproduce

**Comment by maaktweluit** [comment]
Caused by: https://github.com/golemfactory/golem/pull/3171

Propose to solve this by checking if the file exists before calling RPC, if it does not start golem first.
