### ISSUE TITLE
outdated tar.gz dependency

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/golem-electron#453]
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

**Comment by mdtanrikulu** [comment]
@shadeofblue  Could you please provide me the package name which belongs to this dependency? It should be somewhere around of this error.

**Comment by mdtanrikulu** [comment]
Resolved.
