### ISSUE TITLE
Improve Preview UI controls consistency

### ISSUE THREAD

**Issue by mattatgit** [golemfactory/golem-electron#46]
Problem: Preview switch works in different manner to rest of the main UI controls
Solution: Bring into line with other styles

Also: move Preview Window launch button to lower toolbar so it can be accessed without having the Preview on 

Behaviour for Preview on/off
https://app.atomic.io/d/j0kR533j37Yn

**Comment by mdtanrikulu** [comment]
Preview Window Launch button is hidden, until user selects any task from the list. To keep same behaviour in Atomic version, I think preview switch and PWL button should switch place.

**Comment by mattatgit** [comment]
I don't agree with that. The reason why we made this change is that hiding controls is not really good practice, especially for major pieces of the UI like this.The original thinking was that as many task types will not require Preview functions, this was acceptable. But revisting it, i think that is a mistake. PWL button should be visible, but disabled until a task is selected.

**Comment by mdtanrikulu** [comment]
Resolved by 08ef9f381ff32609d56128e54f690e695d70dcf6.

![image](https://user-images.githubusercontent.com/2774845/28032385-8be32630-65aa-11e7-81f6-5699e8b5bd05.png)
