### ISSUE TITLE
Clicking settings when Golem is stopped crashes the application

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#477]
#### Encountered on:
rc 0.18.2, build 3000

checked on Linux, Windows, reproducible

steps to reproduce:
- start Golem
- stop it with "stop/start" button
- click button for app settings
- Golem crashes with blank screen

<img width="1375" alt="screen shot 2018-11-09 at 17 31 06" src="https://user-images.githubusercontent.com/32061891/48286847-3cf12080-e467-11e8-920b-61fafe0a007a.png">

**Comment by mdtanrikulu** [comment]
Resolved by #474.
