### ISSUE TITLE
Cannot connect to Golem network even after enabling port forwarding

### ISSUE THREAD

**Issue by hushabuba** [golemfactory/golem-electron#49]
I followed the guide referenced for port forwarding and I think it worked fine. I checked my firewall to determine if it was blocking the connections and it was not. I am not sure why Golem cannot connect to the network
![screenshot 68](https://user-images.githubusercontent.com/29960774/27932006-ee70b040-6250-11e7-81d7-678926b757b1.png)

**Comment by badb** [comment]
Can you check in your task manager if geth & hyperg are started after you start golem?

**Comment by hushabuba** [comment]
yes they are both running
![screenshot 69](https://user-images.githubusercontent.com/29960774/27932817-f7941fd8-6253-11e7-851e-e2d826100e02.png)

**Comment by badb** [comment]
Can you send us your logs to tech@golem.network? They should be located in your home directory in `.golem/logs/`

**Comment by badb** [comment]
1) It should be port 3282 not 3828. 
2) We figure out that it was a firewall issue.
