### ISSUE TITLE
Newly created tasks show up on list as "finished"

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/golem-electron#496]
Testnet with concent enabled.

The tasks are showing up as finished despite have a `Creating the deposit` status.

**Comment by mdtanrikulu** [comment]
~There is no concent related changes merged yet. I will test it in `concent` branch if anything missing.~

Edit: Seems everything is fine for me. Probably the reason was you didn't have the changes belong to concent. Please check it again.

**Comment by mfranciszkiewicz** [comment]
Resolved in `b0.19.0`

**Comment by shadeofblue** [comment]
^^^ apparently, not ... 

The issue:
RPC reports tasks status: `Creating the deposit`

and at the same time Electron shows:

Task status: Finished
