### ISSUE TITLE
lags in interface when clicking task details for running task

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#498]
When user goes to task details informations are not displayed immediately, instead of it all boxes are blank. It can even take around 50 seconds for informations to show up.

<img width="480" alt="screen shot 2018-12-20 at 13 15 57" src="https://user-images.githubusercontent.com/32061891/50284812-89fae600-045a-11e9-9518-8ea083d83d5b.png">

<img width="964" alt="screen shot 2018-12-20 at 13 11 34" src="https://user-images.githubusercontent.com/32061891/50285671-3e960700-045d-11e9-8652-1cbd4431b1c6.png">

**Comment by mfranciszkiewicz** [comment]
It's not really an issue with GUI - it could transition to the next view earlier and show some kind of loading message, but the node list would be empty for those 50s.

It seems that core's event loop is under heavy load and even retrieving a subtask list is burdensome.
