### ISSUE TITLE
Fatal Error! Failed to execute script golemapp

### ISSUE THREAD

**Issue by ghost** [golemfactory/golem-electron#51]
It's clear installation. After run i get "Fatal Error! Failed to execute script golemapp". Geth is not running in the background but I can run it from cmd.

**Comment by badb** [comment]
Can you send us logs that are located in your home directory in ".golem/logs"?

**Comment by ghost** [comment]
"E:\Program Files (x86)\Golem\logs" is empty

**Comment by badb** [comment]
It should be `C:\Users\<your_user_name>\.golem\logs`

**Comment by ghost** [comment]
It's empty. :(

**Comment by ghost** [comment]
OK, I performed clean installation one more time and i get this in logs.

[golem.txt](https://github.com/golemfactory/golem-electron/files/1133225/golem.txt)

**Comment by badb** [comment]
Ok, your docker machine is not starting properly. What happens if you write "docker-machine start golem" in cmd line?

**Comment by ghost** [comment]
```
starting "golem"...
machine does not exist
```

**Comment by badb** [comment]
https://docs.golem.network/10-troubleshooting.html - check dot number 3

**Comment by ghost** [comment]
[golem.txt](https://github.com/golemfactory/golem-electron/files/1133294/golem.txt)
```
>docker-machine create golem --driver virtualbox
Host already exists: "golem"

>docker-machine start golem
Starting "golem"...
Machine "golem" is already running.

>eval $(docker-machine env golem)
'eval' is not recognized as an internal or external command operable program or batch file
```
Still same problem.

**Comment by badb** [comment]
1) Try just: `docker-machine env golem` then check the last line that is printed out. 
2) Remove `REM` from the line and copy-paste the rest. Should start with `FOR`. 
3) If this works, make sure that geth & hyperg are not running and try to start golem again.

**Comment by ghost** [comment]
```
>docker-machine env golem
@FOR /f "tokens=*" %i IN ('docker-machine env golem') DO @%i
```

It works, thank you! I see that in VirtualBox I have two systems - one named "default" created by golem and one "golem" which was created in cmd. I don't know why it wasn't created automatically with correct name.

Sadly, I get error about router ports but they are open.

**Comment by mdtanrikulu** [comment]
Port error changed as skippable. Resolved with 2cb68510476b3c637ffa8267abcee25fbd485414.

**Comment by jcmax111** [comment]
I have the same issue however mine still isn't fixed

**Comment by maaktweluit** [comment]
hey @jcmax111 

Could you please check and or share your logs? 
windows logs are in `%LOCALAPPDATA%\golem\golem\default\logs`, mac logs are in `~/Library/Application\ Support/golem/default/logs` and linux in `~/.local/share/golem/default/logs`
The file is always called `golem.log`.

When there is no file please check if Openssl and Hyperg are installed correctly and added to the path. For further help on this track please reply what OS you are using.

Have a great day!

Maaktweluit

**Comment by apopovic** [comment]
Log file is not created when i run `golemapp --nogui` only error message "Fatal Error! Failed to execute script golemapp". 
If i start golem from the start menu the GUI shows up but only shows "Starting Golem"...
![image](https://user-images.githubusercontent.com/11003926/35195464-1c177ec4-fec4-11e7-8d7c-7d2e03149536.png)

Here is my log file under %LOCALAPPDATA%\golem\golem\default\logs: 
[golem.log](https://github.com/golemfactory/golem-electron/files/1649838/golem.log)

What is openssl and Hyperg? 
It is not mentioned here:
[https://github.com/golemfactory/golem/wiki/Installation](https://github.com/golemfactory/golem/wiki/Installation)

**Comment by mdtanrikulu** [comment]
Hey @popovic85,

You have this error on your log;
`DockerMachine: failed to check status: Command '['docker-machine', 'status', 'golem']' returned non-zero exit status 1.'`

Follow the steps;

1- Please make sure if you already have docker and running well.
2- Then please check if golem container created and running;
`docker-machine ls`

3- If your container status (state) is `Stopped` or `Error`, restart your container with;
`docker-machine restart golem`

4a - If restart is successful, set your environment. To do that, type;
`docker-machine env golem`
This will show you some information and at the end of this info you'll find the code you need to execute.
For windows: `@FOR /f "tokens=*" %i IN ('docker-machine env golem') DO @%i`
For mac and linux: `eval $(docker-machine env golem)`
You're done and ready to start golem.

4b. If restart is not successful, remove exist golem instance by;
`docker-machine rm golem` and type `yes`
Then start golem, it'll create new instance for you.

**Comment by apopovic** [comment]
Hey @mdtanrikulu 
Thank you very much, it looks like i am connected to golem now!

**I did the folowing:**
`docker-machine ls` -> "Errors" machine does not exist
`docker-machine rm golem` - as mentioned in the fourth step and restarting golem make it work.
![capture](https://user-images.githubusercontent.com/11003926/35196860-2142d646-fed8-11e7-9b7b-0182b340fae1.JPG)

NOTE:
I am just concerned why i get so many "infos" in the log file stating `TOO MANY PEERS DROPPING CONNECTION` and `DISCONNECTING`.
Here is my log file:
[golem.log](https://github.com/golemfactory/golem-electron/files/1649969/golem.log)
