### ISSUE TITLE
Implement frame restart as subtask restart

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/golem-electron#522]
Instead of calling `comp.task.subtasks.frame.restart`, call `comp.task.restart_subtasks` with an array of subtasks that encompass the specific frame.

If a subtask includes several frames, restart this subtask (we don't care too much that several frames will get restarted) -> it's an issue to be solved by creating better formed tasks and not a problem to be solved by Golem and/or Electron

**Comment by mdtanrikulu** [comment]
The restart flow will be added as well, as subtask list has.
