### ISSUE TITLE
Act as requestor only, resets after restart

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/golem-electron#524]
The slider on the main page of the GUI keeps resetting after restarting the Golem GUI. I assume this is a bug and not a feature. Pardon if im wrong.

**Comment by mdtanrikulu** [comment]
Confirmed, it's not getting the last state after restart. Thank you for the feedback, I will patch it.

Note: It's only a UI issue, even if it goes to disable after restart the actual status is enabled.

**Comment by cryptobench** [comment]
Yeah, I just noticed when I booted it up now that it remembers it besides the UI. Thank you. :-)
