### ISSUE TITLE
Support graceful shutdown

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/golem-electron#527]
Golem core includes logic for shutting down gracefully (if there are any tasks running, core is put into a state where it does not accept any new tasks and waits for the pending ones to finish before shutting down). This state can be toggled using the RPC `golem.graceful_shutdown`.

This could be utilised in Electron, with shutdown state being triggered on exit and toggled off (if necessary) when Electron is started again.

**Comment by mdtanrikulu** [comment]
So the only required parameter is boolean I suppose?

**Comment by kmazurek** [comment]
@jamuszyn As discussed, this will require some design work from you. @mdtanrikulu What parameter do you mean here?

**Comment by mdtanrikulu** [comment]
@zakaprov For the RPC usage, to toggle etc. 
```js
graceful_shutdown(true, "some other paramter if needed")
```

**Comment by kmazurek** [comment]
The relevant RPC (`golem.graceful_shutdown`) takes no parameters, it works as a simple toggle. The status for the shutdown is returned in the response from the RPC (enum `ShutdownResponse` in Golem core). Any feedback for the user should be based on this response.
