### ISSUE TITLE
blank in terms of use for concent

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#534]
## Description

**Golem Version**: 0.19.0; 0.19.1

**Golem-Messages version**  2.24.3

**Electron version** 0.1.18; 0.1.19

**OS** Any

**Mainnet/Testnet**: Testnet

**Description of the issue**:

There should be some info added or  at leas less blank space - no scrollbar. It looks like something went wrong or is missing.

**Screenshots**:

<img width="491" alt="Screen Shot 2019-03-20 at 19 09 47" src="https://user-images.githubusercontent.com/32061891/54710622-62deae00-4b48-11e9-811c-3afcf04d5e1b.png">

**Comment by jamuszyn** [comment]
Solved in https://github.com/golemfactory/golem/pull/4072
