### ISSUE TITLE
on Windows printing password generates file with no extension

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#535]
## Description

**Golem Version**: 0.19.1

**Golem-Messages version** (leave empty if unsure): 2.24.3

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Windows

**Branch** (if launched from source): -

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

On Windows when user is printing password to the file (pdf) file is created with no extension. To open file it is needed to add it manually.

**Comment by shadeofblue** [comment]
@ederenn does it happen all the time? you said on the local channel that it only happens the second time... 

Please, remember to define reliable "Steps to reproduce" problem in each bug report

**Comment by mdtanrikulu** [comment]
It should be fixed in newest RC, as @ZmijaWA tested today.
