### ISSUE TITLE
Excessive CPU usage after running Electron for longer period

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/golem-electron#543]
## Description
After Golem has been running for 10-20 hours hours, i've been noticing that it suddenly uses a lot of CPU usage. It can go on for around 5 hours I would assume and then the CPU usage is back to normal.

**Electron version**:
Not sure - the one that comes with default install.sh script for Ubuntu version 0.19.1
**Golem Version**:
0.19.1

**Golem-Messages version** (leave empty if unsure):

**OS** [e.g. Windows 10 Pro]:
Ubuntu 18.04

**Branch** (if launched from source):

**Mainnet/Testnet**:
Mainnet

**Description of the issue**:
Sudden CPU usage spike with no explanation for it whatsoever. No tasks running as I checked the field with I only wanna act as a requestor

**Actual result**:
Spike in CPU usage for longer period of time.

**Screenshots**:
![image](https://user-images.githubusercontent.com/33448819/56128899-30767400-5f81-11e9-9bfb-df39552a362d.png)

## Steps To Reproduce
1. Launch Golem Mainnet
2. Check act as requestor only.
3. Wait

## Expected behavior
Sudden spike in CPU usage for a longer period of time.

## Logs and any additional context
Logs only shows connecting to peer n , in that time period.

**Comment by mdtanrikulu** [comment]
Hello @cryptobench !  Could you tell me which screen/tab/section was displaying in the app while waiting? Was it "Network", "Tasks" or "Settings" ?

**Comment by cryptobench** [comment]
Hey, @mdtanrikulu ! The issue just appeared again. New screenshots
![image](https://user-images.githubusercontent.com/33448819/56136554-4ee56b00-5f93-11e9-991b-0b92eb7bcb29.png)
![image](https://user-images.githubusercontent.com/33448819/56136569-56a50f80-5f93-11e9-802d-d87be7d3cda3.png)

**Comment by mdtanrikulu** [comment]
@cryptobench Thank you! I will take care about it.

**Comment by cryptobench** [comment]
Thanks for looking into it. I would love to provide more info, but nothing really stands out to me what could cause it. Restarting Golem always resolves it.

**Comment by mdtanrikulu** [comment]
This commit (7add06a2ba73e0b7cc9143de8c7ac728d47e29ba) solved part of the issue.
Unnecessary updates are removed and/or restricted. The change is already landed with Golem v0.19.2.
So please let me know if you have a chance to observe it.

**Comment by cryptobench** [comment]
Nice! I honestly haven't noticed this issue for some time so that most likely fixed the issue. Thanks for looking into it! @mdtanrikulu
