### ISSUE TITLE
problems with docker-machine during upgrade from 19.1 to 19.2 are not reported in electron

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#550]
## Description

**Golem Version**: 0.19.2

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used): 0.1.20

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source):  -

**Mainnet/Testnet**: mainnet 

**Description of the issue**:

After regular upgrade from Golem 0.19.1 to 0.19.2 there are problems with docker machine. Golem hangs on information: Setting docker environment. In logs it is shown that docker-machine has crashed. This is not reported in GUI.

**Actual result**:

Golem won't launch and user does not know that something went wrong, until checking the logs

**Screenshots**:

![Screenshot from 2019-05-22 20-17-08](https://user-images.githubusercontent.com/32061891/58198561-c3b46f00-7cce-11e9-8c6a-1f5a2f92f339.png)

## Steps To Reproduce
 Machine with Golem 19.1 installed is needed

1. Download 0.19.2 installer
2. Run whole installation
3. Launch Golem
4. It will hang on Setting environment modal
5. Check logs

## Expected behavior

When there are encountered problems with docker it should be shown in GUI with modal.

## Logs and any additional context

```
2019-05-22 11:13:47 INFO     golem.node                          Got password
2019-05-22 11:13:47 INFO     golem.docker.hypervisor.hyperv      Hyper-V: Restoring VM golem ...
2019-05-22 11:14:20 WARNING  golem.docker.hypervisor.docker_machine DockerMachine: failed to update env for VM: Command '['docker-machine', '--native-ssh', 'env', '--shell', 'cmd', 'golem']' returned non-zero exit status 1.
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by mdtanrikulu** [comment]
If golem doesn't publish status of docker in error case, the GUI won't be able to interpret it. So it seems like a core issue not the GUI. I will make a referenced issue on Golem repo.
