### ISSUE TITLE
Onboarding message about port forwarding should point to troubleshooting docs page. 

### ISSUE THREAD

**Issue by badb** [golemfactory/golem-electron#57]
First onboarding screen shows message about ports forwarding, but points to docs.golem.network and not to specific doc page where port forwarding is described.

**Comment by maaktweluit** [comment]
tried to fix this, but its already done :D 

on `master` this is still wrong.
on `dev` it is fixed ([code here](https://github.com/golemfactory/golem-electron/blob/dev/src/components/onboarding/steps/Step1.js))

maybe the issue can be tagged for next milestone?

**Comment by mdtanrikulu** [comment]
We left `master`, using `dev` as default. 
Redirection seems working well, I think we can close this issue.
