### ISSUE TITLE
The ports are unreachable

### ISSUE THREAD

**Issue by RodrigoNovais** [golemfactory/golem-electron#575]
## Description

**Golem 0.20.1 Mainnet** running on **Windows 10 Pro**

**Description of the issue**:
I can't workaround of the unreachable ports issue
I checked my firewall, allowed port forwarding and also search on r/GolemProject
Is there something I can try to solve it?

**Screenshots**:
![Captura de Tela (1)](https://user-images.githubusercontent.com/11841314/62509996-d45f8600-b7e3-11e9-94f5-0d3daf2b6bcc.png)
![Captura de Tela (2)](https://user-images.githubusercontent.com/11841314/62509998-d45f8600-b7e3-11e9-8ce2-60c7eda4b8c1.png)
![Captura de Tela (3)](https://user-images.githubusercontent.com/11841314/62509999-d4f81c80-b7e3-11e9-8cd5-f9260aacc5a9.png)
![Captura de Tela (4)](https://user-images.githubusercontent.com/11841314/62510218-94e56980-b7e4-11e9-9faa-c4466c722d76.png)

**Comment by etam** [comment]
Please check if external IP of your router matches IP reported by "Golem Network Check" website.

It might be the case that your ISP keeps you behind a NAT. (for example I have this at home)

**Comment by RodrigoNovais** [comment]
I believe your talking about that info
How can I know about NAT and workaround it?

![image](https://user-images.githubusercontent.com/11841314/62564647-9f8f1580-b85b-11e9-8cd7-6725e9e72fd4.png)

**Comment by etam** [comment]
IPs are the same, so it's not NAT.

I'm sorry, but I'm out of ideas.

**Comment by ktomala** [comment]
You have golemapp and hyperg blocked in your firewall. That's the reason your ports are unreachable.

**Comment by RodrigoNovais** [comment]
I have disabled those rules and still not running

![image](https://user-images.githubusercontent.com/11841314/62639966-f3126980-b916-11e9-84a9-9389746d3f9c.png)

**Comment by ktomala** [comment]
@RodrigoNovais you do not disable them. You have to enable them and allow access.

**Comment by RodrigoNovais** [comment]
@ktomala 
I had to stop dealing with it for a while
I didn't realise that the rules was blocking the access but I still having problems to connect

It connects for just one node and that "waiting for configuration" warning doesn't go away
But for now, the issue I have complained was solved, I gonna close it

![image](https://user-images.githubusercontent.com/11841314/65695911-bfb6a600-e04e-11e9-8768-67b206888385.png)

**Comment by andresdica** [comment]
Hi rodrigo, I wonder if you were able to find the soltution to the unreachable ports for golem. I´m having the same problem here. thanks.

**Comment by RodrigoNovais** [comment]
@andresdica
Sorry, I had no time to deal with it anymore.
You can tell by the time I took to read this message XD
