### ISSUE TITLE
Include Build information in Settings

### ISSUE THREAD

**Issue by mattatgit** [golemfactory/golem-electron#58]
![build number](https://user-images.githubusercontent.com/6858525/28101351-56581662-670b-11e7-8982-155913049c81.png)

At the moment, we cannot get Golem to connect to any nodes, even with ports open, at least on our office network. So we are constantly updating builds as they come out. However, the only way to know which build we have is by looking in the terminal output during the install process. 

Being able to see more than just "Brass Golem V0.1" but also the build information will probably be useful to everyone during beta testing and probably well beyond so i would suggest adding it.

**Comment by mdtanrikulu** [comment]
We show Build version instead of UI version. So, we'll determine the version UI with it. See 2410ec12113e3b042dc77b12e78bdae4adf0fd69.
