### ISSUE TITLE
gWASM: the number of subtasks

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/golem-electron#585]
## Description

**Golem Version**: 0.20.2 (current)

**Electron version**: ?

**Mainnet/Testnet**: Testnet

**Description of the issue**:

Number of subtasks on the list of completed tasks. For gWASM the display is misleading. GUI shows 70 subtasks, but there were 35 subtasks actually. But there were 70 jobs because of VbR. So it should be shown 'Subtasks: 35 (x2)' or 'Subtasks: 35 Jobs:70'. I prefer the first one.

**Screenshots**:

![g2](https://user-images.githubusercontent.com/29129196/64271616-e5fc9080-cf3d-11e9-9f70-7b2dfe393564.png)

**Comment by mdtanrikulu** [comment]
Fixed by #4702.
