### ISSUE TITLE
Tasks view should probably be disabled until system has nodes connected

### ISSUE THREAD

**Issue by mattatgit** [golemfactory/golem-electron#59]
Currently user can click over to tasks and try to add a task, and get as far as doing all the setup, only to find that nothing works. Disabling the Tasks view controls until the system is connected to active nodes would probably be a good idea

**Comment by mdtanrikulu** [comment]
Actually users able to add task while golem stopped. The thing is, system won't add those tasks to the list until golem starts. So, maybe it's a good approach to disable create task if golem stops.

**Comment by mattatgit** [comment]
Ok that sounds reasonable.

**Comment by mdtanrikulu** [comment]
Resolved #169.
