### ISSUE TITLE
Forms for a dummy task needed

### ISSUE THREAD

**Issue by inexxt** [golemfactory/golem-electron#62]
A "dummy', useful-for-debugging-and-implementation-example task is developed, and it needs some UI.

The input file is supposed to be an ordinary text file.
After the user select that file, he should be greeted with short task description and prompted for:
 1. Difficulty factor (from 0 to 2^32, probably would be better to show it on a logarithmic scale, with some label on what is the required time prediction - if this counter is set on x, then the task will take about 2^(-15)*x seconds).
 2. Number of subtasks
 3. Length of subtask-specific data (in bits) - every subtask has to calculate PoW based on shared data file (the input file received at the beginning) concatenated with subtask-specific data, which is chosen at random during task creation. This parameter sets the size of that additional data send to providers.
 4. Timeouts forms, as it is with rendering
 5. Price form, as it is with rendering

**Comment by mdtanrikulu** [comment]
Added 9ff6e57cb0044a1bfdc679c5f35a609458dd2534.
