### ISSUE TITLE
deposit pagination is broken for older entries

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#627]
## Description

**Golem Version**: 0.22.0

**Golem-Messages version** (leave empty if unsure): 3.14.1

**Electron version**: 0.2.3-95-gbb68f48

**OS** [e.g. Windows 10 Pro]: Linux

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

If there are many entries on transaction history list, deposit appears in deposit tab only after scrolling all transactions tab.

**Screenshots**:

![Screenshot from 2020-01-09 17-04-37](https://user-images.githubusercontent.com/32061891/72093404-9592a680-3314-11ea-8609-008cea864d22.png)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by mdtanrikulu** [comment]
Fixed.
