### ISSUE TITLE
Default output folder not loaded from settings when creating task

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/golem-electron#63]
When creating a new task in 0.7.1 on windows 10:

![creating-a-new-task](https://user-images.githubusercontent.com/10008353/28238750-eac6b7a8-695a-11e7-86ac-66a77585e747.PNG)

`!==`

What is configured in the settings:
![settings](https://user-images.githubusercontent.com/10008353/28238753-f4e24676-695a-11e7-88d1-85d8de4bd5fa.PNG)

Settings where set in 0.6.0 with the UI, updated recently to 0.7.0, and now to 0.7.1.

**Comment by mdtanrikulu** [comment]
This is just an UI problem, if you keep "output to" input blank (not required) while creating task, it won't show you any problem and will send your default output location as output path.

**Comment by maaktweluit** [comment]
Thanks for the reply!
Trivial issue then, also when selecting the output folder each time it remembers the last chosen location.

**Comment by mdtanrikulu** [comment]
Yes, that's right and it's not an issue. Instead of forcing users each time to choose their work environment from the beginning, last position shown as an alternative.
