### ISSUE TITLE
UI - underline is shifted

### ISSUE THREAD

**Issue by ghost** [golemfactory/golem-electron#69]
Go to "settings" and hover "network" or "tasks" - http://i.imgur.com/IWXzYkS.jpg

Maybe icons on the right "new task/docs/settings" should also be underlined for better readability?

**Comment by mdtanrikulu** [comment]
Thanks for feedback. 
 On new update, there won't be underline move when hover to the menu. Instead, when you click menu item, underline will slide there. See #40.

**Comment by mdtanrikulu** [comment]
Done by 6113504c3821b4baa3962fc1dd0eced5b6821a8f.
