### ISSUE TITLE
preview and window resizing

### ISSUE THREAD

**Issue by paulperegud** [golemfactory/golem-electron#8]
![out](https://user-images.githubusercontent.com/247162/27485686-01bb8058-582e-11e7-9286-60e701efc0c3.gif)

**Comment by badb** [comment]
Disabling preview toggle won't solve this problem. It will still occur when there is preview. We need different solution. Maybe it's possible to save last app height?

**Comment by mdtanrikulu** [comment]
So basically, if current height of the application greater than or equal to preview active height, there won't be any change but if lesser, there will be. Here 3daf2e2ab59047a6340089c49f779277db9ed735.

![resize-issue](https://user-images.githubusercontent.com/2774845/27963186-8588d8fc-6334-11e7-813f-8cf0984e7c13.gif)
