### ISSUE TITLE
If there are two displays connected, the window will be created in the middle of the joined desktop

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/golem-electron#86]
i.e., usually at the border of the left and right display

**Comment by mdtanrikulu** [comment]
Is that application itself or second (preview) screen?

**Comment by marmistrz** [comment]
The first window, with the intro

**Comment by mdtanrikulu** [comment]
This seems related with electron itself for the [Cinnamon environment](https://github.com/linuxmint/Cinnamon). You can create an issue about it [here](https://github.com/electron/electron/issues).
