### ISSUE TITLE
welcome screen, first launch of golem

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#98]
Info on welcome screen (descriptions for network, tasks, node) is misleading. There 
should be added some header like "hint" "tips" or "introduction". Current screen - plain description - makes an impression that you need to set something at this point. Eg. node. On this screen it is possible to type user's node name, instead of  "Anonymous Golem". Nothing is set, nothing is saved. There is no info that was just an example. Later on, one is wondering if node name was set anywhere or if it's needed to be typed again.

**Comment by mdtanrikulu** [comment]
Welcome screen improved with #113.
